# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-01 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=500)),
                ('title', models.CharField(choices=[('นาย/Mr.', 'นาย'), ('นาง/Mrs.', 'นาง'), ('นางสาว/Ms.', 'นางสาว')], max_length=1)),
                ('first_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=500)),
                ('birth_date', models.DateField()),
            ],
        ),
    ]
