# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-01 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecosystem', '0002_auto_20161101_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='title',
            field=models.CharField(choices=[('นาย/Mr.', 'นาย/Mr'), ('นาง/Mrs.', 'นาง/Mrs'), ('นางสาว/Ms.', 'นางสาว/Ms')], max_length=500),
        ),
    ]
