# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-02 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecosystem', '0005_auto_20161102_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='postal_code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='telephone_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
