# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-02 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecosystem', '0007_auto_20161102_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelregister',
            name='channel',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Lazada', 'Lazada'), ('Website', 'Website'), ('สาขาใกล้บ้าน', 'สาขาใกล้บ้าน'), ('งานแสดงสินค้า', "'งานแสดงสินค้า")], default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelregister',
            name='recommendation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
